try(require("shiny")||install.packages("shiny"))
try(require("mlogit")||install.packages("mlogit"))
try(require("dplyr")||install.packages("dplyr"))
try(require("tidyr")||install.packages("tidyr"))
try(require("readxl")||install.packages("readxl"))
try(require("jsonlite")||install.packages("jsonlite"))
try(require("tidyselect")||install.packages("tidyselect"))

library("shiny")
library("mlogit")
library("dplyr")
library("tidyr")
library("readxl")
library("jsonlite")
library("tidyselect")
